apiVersion: apps/v1
kind: Deployment
metadata:
  name: voxchain-frontend
  namespace: voxchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voxchain-frontend
  template:
    metadata:
      labels:
        app: voxchain-frontend
    spec:
      containers:
        - name: frontend
          image: southamerica-east1-docker.pkg.dev/voxchain/voxchain-images/voxchain-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
