apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: voxchain-api
  namespace: voxchain
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: voxchain-api
  namespaceSelector:
    matchNames:
      - voxchain
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
