apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-proxy
  namespace: g-git-push-cv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-proxy-role
  namespace: g-git-push-cv
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["worker-modes"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-proxy-binding
  namespace: g-git-push-cv
subjects:
  - kind: ServiceAccount
    name: backend-proxy
    namespace: g-git-push-cv
roleRef:
  kind: Role
  name: backend-proxy-role
  apiGroup: rbac.authorization.k8s.io