apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: g-git-push-cv

resources:
  - namespace.yaml
  - worker-config.yaml
  - rabbitmq-ca-secret.yaml
  - rabbitmq-credentials-secret.yaml
  - redis-credentials-secret.yaml
  - worker-deployment.yaml
  - worker-hpa.yaml

  - pool-coordinator-deployment.yaml
  - pool-coordinator-service.yaml
  - pool-miner-deployment.yaml
  - pool-miner-hpa.yaml
