apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-ca
  namespace: g-git-push-cv
type: Opaque
data:
  ca.crt: ""  # Se llena en CI/CD con `kubectl create secret generic rabbitmq-ca --from-file=ca.crt=./certs/ca.crt`
