apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: g-git-push-cv
type: Opaque
stringData:
  username: ""    # Se llena en CI/CD desde GitHub Secrets
  password: ""    # Se llena en CI/CD desde GitHub Secrets
  keda-host: ""   # AMQPS URL completa para KEDA: amqps://user:pass@host:5671/
