apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: g-git-push-cv
type: Opaque
stringData:
  username: "voxchain-worker"
  password: "CHANGE_ME_IN_PROD"
  keda-host: "amqps://voxchain-worker:CHANGE_ME_IN_PROD@placeholder.voxchain.local:5671/"
