apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-tls
  namespace: voxchain
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: rabbitmq-tls
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: rabbitmq-ca-crt
    - secretKey: rabbitmq-cert.pem
      remoteRef:
        key: rabbitmq-tls-crt
    - secretKey: rabbitmq-key.pem
      remoteRef:
        key: rabbitmq-tls-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: voxchain
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rabbitmq-user
    - secretKey: password
      remoteRef:
        key: rabbitmq-pass
    - secretKey: erlang-cookie
      remoteRef:
        key: rabbitmq-erlang-cookie
